variables:
  PROJECT_NAME: "zella/http-from-pubsub"
stages:
  - test
  - publish

test:
  stage: test
  image: "hseeberger/scala-sbt:11.0.8_1.3.13_2.13.3"
  variables:
    SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
    COURSIER_CACHE: sbt-cache/coursier
  script:
    - sbt test
    - sbt assembly
  cache:
    untracked: false
    paths:
      - "sbt-cache/ivy/cache"
      - "sbt-cache/boot"
      - "sbt-cache/sbtboot"
      - "sbt-cache/target"
      - "sbt-cache/coursier"
  artifacts:
    paths:
      - build
    expire_in: 1 days

publish:
  stage: publish
  image: "docker:19"
  before_script:
    - echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
  script:
    - export VERSION=$(cat version)
    - cd build/
    - docker build --pull -f Dockerfile -t $PROJECT_NAME:$VERSION -t $PROJECT_NAME:latest .
    - docker push $PROJECT_NAME
  only:
    - master
